### ISSUE TITLE
授業内で指示をされたことを守る

### ISSUE THREAD

**Issue by makora9143** [yuyamasaki/itclass-final#1]
一応授業で，「 `README.md`を作成して，その中に最終課題の内容をかく．」
という指示をしていると思うので，それを守ってください．

**Comment by yuyamasaki** [comment]
本当に申し訳ありません。授業で聞き逃しておりました。修正して再提出致しますのでご確認のほど、恐れ入りましがよろしくお願いいたします。

**Comment by makora9143** [comment]
一応 `README.md` は編集できているみたいなのだけど，ちゃんと最終課題の内容を書いてくださいね〜

**Comment by yuyamasaki** [comment]
ご連絡ありがとうございます！かしこまりました。これから最終課題内容を詳しく書いていきたいと思います。

**Comment by makora9143** [comment]
内容を埋めたらまたコメントするので，頑張って書いてください！
一応意図は伝わったようなので，一旦このissueはcloseしちゃいますね．
